

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StoreWebservice
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class StoreContainer : DbContext
{
    public StoreContainer()
        : base("name=StoreContainer")
    {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer> CustomerSet { get; set; }

    public virtual DbSet<Order> OrderSet { get; set; }

    public virtual DbSet<Product> ProductSet { get; set; }

}

}

